services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      DD_AGENT_HOST: datadog-agent
      DD_ENV: local
      DD_SERVICE: crash-repro
      DD_VERSION: "1.0"
      DD_TRACE_AUTO_FLUSH_ENABLED: "true"
      DD_TRACE_GENERATE_ROOT_SPAN: "true"
      DD_PROFILING_ENABLED: "true"
      DD_PROFILING_ALLOCATION_ENABLED: "true"
      DD_PROFILING_TIMELINE_ENABLED: "true"
      RUN_WITH_GDB: "false"
    depends_on:
      - datadog-agent
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined

  datadog-agent:
    image: datadog/agent:7
    environment:
      DD_API_KEY: "dummy000000000000000000000000000"
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_USE_DOGSTATSD: "false"
      DD_LOGS_ENABLED: "false"
      DD_PROCESS_AGENT_ENABLED: "false"
